#server:
#  servlet:
#    contextPath: /laptop/service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/karthi
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 7000
